#!/bin/bash

# create-pr.sh - 创建 Pull Request
# 用法: ./create-pr.sh <分支名> <任务ID> [标题] [描述]

set -e

# 参数
BRANCH="$1"
TASK_ID="$2"
TITLE="${3:-Auto-generated PR from Claude Code}"
DESCRIPTION="${4:-}"

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Creating Pull Request ===${NC}"

# 检查 gh CLI 是否安装
if ! command -v gh &> /dev/null; then
    echo -e "${RED}Error: GitHub CLI (gh) is not installed${NC}"
    echo "Install it with: sudo apt install gh"
    exit 1
fi

# 检查 gh 是否已认证
if ! gh auth status &> /dev/null; then
    echo -e "${YELLOW}Warning: gh is not authenticated. Please run: gh auth login${NC}"
    exit 1
fi

# 获取当前仓库信息
REPO_URL=$(git config --get remote.origin.url)
REPO_NAME=$(basename -s .git "$REPO_URL")

echo "Repository: $REPO_NAME"
echo "Branch: $BRANCH"
echo "Task ID: $TASK_ID"

# 如果没有提供描述，从最近的提交生成
if [ -z "$DESCRIPTION" ]; then
    DESCRIPTION="## 🤖 AI-Generated Changes

This PR was automatically created by Claude Code agent.

### Task ID
\`$TASK_ID\`

### Changes
$(git log --oneline HEAD~5..HEAD 2>/dev/null || git log --oneline -5)

### Files Modified
$(git diff --stat HEAD~1 2>/dev/null || echo "No changes detected")

---
*Generated by testclaude team*"
fi

# 创建 PR
echo -e "${GREEN}Creating PR...${NC}"
PR_URL=$(gh pr create \
    --title "$TITLE" \
    --body "$DESCRIPTION" \
    --base master \
    --head "$BRANCH" \
    --label "ai-generated,claude-code" \
    2>&1)

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ PR created successfully!${NC}"
    echo "$PR_URL"
    
    # 输出 PR URL 供后续使用
    echo "PR_URL=$PR_URL"
    exit 0
else
    echo -e "${RED}Failed to create PR: $PR_URL${NC}"
    exit 1
fi
